version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: notes_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes_network

volumes:
  postgres_data:
    driver: local

networks:
  notes_network:
    driver: bridge
